localiztion:
    node_edge_localizer:
        INIT_YAW: 3.14
        INIT_NODE0_ID: 0
        INIT_NODE1_ID: 1
        INIT_PROGRESS: 0
        ENABLE_TF: true
        ENABLE_ODOM_TF: true
        USE_OBSERVED_POSITION_AS_ESTIMATED_POSE: true
