localiztion:
    node_edge_localizer:
        INIT_YAW: -1.57
        INIT_NODE0_ID: 0
        INIT_NODE1_ID: 1
        INIT_PROGRESS: 0
        ENABLE_TF: true
        ENABLE_ODOM_TF: true
        USE_OBSERVED_POSITION_AS_ESTIMATED_POSE: true
recognition:
    road_recognizer:
        road_cloud_publisher:
            INTENSITY_LOWER_THRESHOLD: 20

